swagger: '2.0'
info:
  title: location-service
  version: 0.0.1
  description: location-service
  x-ibm-name: location-service
paths:
  /test:
    get:
      description: location-service app
      operationId: test
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
        "405":
          description: "Invalid input"
        "404":
          description: "Not Found"
  /location:
    get:
      description: location-service app
      operationId: location
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
        "405":
          description: "Invalid input"
        "404":
          description: "Not Found"
  /:
    get:
      description: location-service app
      operationId: init
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
        "405":
          description: "Invalid input"
        "404":
          description: "Not Found"
    post:
      description: location-service app
      operationId: create
      consumes:
      - "application/text"
      produces:
      - "application/text"
      responses:
        "200":
          description: "Success"
schemes:
  - http
  - https
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
host: location-app-git-openshift.itzroks-663002b1mb-xbphnt-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud

